<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net35</TargetFramework>
    <AssemblyName>SRDFPlugin</AssemblyName>
    <RootNamespace>ShadowrunDragonfallLanguageEngage.Chinese</RootNamespace>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShadowrunDragonfallLanguageEngage.Contract\ShadowrunDragonfallLanguageEngage.Contract.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="cedict\CEDictText.txt" />
  </ItemGroup>

</Project>
